/*
 * This source file was generated by the Gradle 'init' task
 */
package org.quotely;

import org.junit.Test;
import static org.junit.Assert.*;

import java.io.IOException;

public class AppTest {
    @Test public void englishQuotesWork() throws Exception{

        Quote quote = Quote.NewQuote("en");
        assert quote.getQuoteAuthor() != "";
        assert quote.getQuoteText() != "";

    }

    @Test public void russianQuotesWork() throws Exception{
        Quote quote = Quote.NewQuote("ru");
        assert quote.getQuoteAuthor() != "";
        assert quote.getQuoteText() != "";

    }    
}
